In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from ast import literal_eval
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
import warnings
warnings.filterwarnings('ignore')
import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['movies_metadata.csv', 'ratings_small.csv', 'keywords.csv', 'links_small.csv', 'links.csv', 'ratings.csv', 'credits.csv']

In [2]:
md = pd.read_csv('../input/movies_metadata.csv')
md.head()

   adult    ...     vote_count
0  False    ...         5415.0
1  False    ...         2413.0
2  False    ...           92.0
3  False    ...           34.0
4  False    ...          173.0

[5 rows x 24 columns]

In [3]:
md['genres'] = md['genres'].fillna('[]').apply(literal_eval).apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])
md['year'] = pd.to_datetime(md['release_date'], errors='coerce').apply(lambda x: str(x).split('-')[0] if x != np.nan else np.nan)

### Movie Description Based Recommender

In [4]:
# We are going to use much more suggestive metadata than Overview and Tagline.

links_small = pd.read_csv('../input/links_small.csv')
links_small = links_small[links_small['tmdbId'].notnull()]['tmdbId'].astype('int')

In [5]:
links_small.head()

0      862
1     8844
2    15602
3    31357
4    11862
Name: tmdbId, dtype: int64

In [6]:
# Define a convert_int() function 
def convert_int(x):
    try:
        return int(x)
    except:
        return np.nan

In [7]:
# Convert the id's in the id column to interger
md['id'] = md['id'].apply(convert_int)
md[md['id'].isnull()]

                                                   adult ...  year
19730                                 - Written by Ørnås ...   NaT
29503   Rune Balot goes to a casino connected to the ... ...   NaT
35587   Avalanche Sharks tells the story of a bikini ... ...   NaT

[3 rows x 25 columns]

In [8]:
# Removing the rows that have null values in the id column
md = md.drop([19730, 29503, 35587])

In [9]:
# Declaring the 'id' column as integer
md['id'] = md['id'].astype('int')

In [10]:
# We have 9099 movies avaiable in our small movies 
# metadata dataset which is 5 times smaller than our 
# original dataset of 45000 movies.
smd = md[md['id'].isin(links_small)]
smd.shape

(9099, 25)

### Movie Description Based Recommender

In [11]:
# filling missing values in tagline and description columns
smd['tagline'] = smd['tagline'].fillna('')  # fill the empty data points in tagline column
smd['description'] = smd['overview'] + smd['tagline']  # Combining columns overview and tagline
smd['description'] = smd['description'].fillna('')

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from surprise import Reader, Dataset, SVD, evaluate

In [13]:
# Converts a collection of raw documents to a matrix of TF-IDF features
tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df = 0, stop_words='english')
tfidf_matrix = tf.fit_transform(smd['description'])

In [14]:
tfidf_matrix.shape

(9099, 268124)

In [15]:
# I will be using the Cosine Similarity to calculate a numeric quantity 
# that denotes the similarity between two movies. 
# Since we have used the TF-IDF Vectorizer, calculating the Dot Product 
# will directly give us the Cosine Similarity Score. Therefore, we will use 
# sklearn's linear_kernel instead of cosine_similarities since it is much faster.

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [16]:
cosine_sim[0]

array([1.        , 0.00680476, 0.        , ..., 0.        , 0.00344913,
       0.        ])

In [17]:
# We now have a pairwise cosine similarity matrix for all the movies in our dataset. 
# The next step is to write a function that returns the 30 most similar movies based 
# on the cosine similarity score.

smd = smd.reset_index()
titles = smd['title']  # Defining a new variable title
indices = pd.Series(smd.index, index = smd['title'])  # Defining a new dataframe indices

In [18]:
smd.head()

   index                        ...                                                                description
0      0                        ...                          Led by Woody, Andy's toys live happily in his ...
1      1                        ...                          When siblings Judy and Peter discover an encha...
2      2                        ...                          A family wedding reignites the ancient feud be...
3      3                        ...                          Cheated on, mistreated and stepped on, the wom...
4      4                        ...                          Just when George Banks has recovered from his ...

[5 rows x 27 columns]

In [19]:
# Defining a function that returns 30 most similar movied bases on the cosine 
# similarity score
def get_recommendations(title):
    idx = indices[title]  # Defining a variable with indices
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse = True)
    sim_scores = sim_scores[1: 31]  # Taking the 30 most similar movies
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]  # returns the title based on movie indices

In [20]:
# Getting the top recommendations for a few movies 
get_recommendations('Transformers').head(10)

7240    Transformers: Revenge of the Fallen
3204            The Transformers: The Movie
3881                               I Am Sam
8585        Transformers: Age of Extinction
7817       Burn Notice: The Fall of Sam Axe
6255                                   Stay
7807         Transformers: Dark of the Moon
7374                               Brothers
2761         National Lampoon's Last Resort
591                       Feeling Minnesota
Name: title, dtype: object

In [21]:
# Our system is able to identify it as a Batman film and subsequently recommend 
# other Batman films as its top recommendations.
get_recommendations('The Dark Knight').head(10)

7931                      The Dark Knight Rises
132                              Batman Forever
1113                             Batman Returns
8227    Batman: The Dark Knight Returns, Part 2
7565                 Batman: Under the Red Hood
524                                      Batman
7901                           Batman: Year One
2579               Batman: Mask of the Phantasm
2696                                        JFK
8165    Batman: The Dark Knight Returns, Part 1
Name: title, dtype: object

### Metadata Based Recommender

### We will build a more sophisticated recommender that takes genre, keywords, cast and crew into consideration.

### To build our standard metadata based content recommender, we will need to merge our current dataset with the crew and the keyword datasets.

In [22]:
credits = pd.read_csv('../input/credits.csv')
keywords = pd.read_csv('../input/keywords.csv')

In [23]:
# Converting the keywords's id column to integer
keywords['id'] = keywords['id'].astype('int')
credits['id'] = credits['id'].astype('int')
md['id'] = md['id'].astype('int')

In [24]:
md.shape

(45463, 25)

In [25]:
# Merging teh credits and keywords DataFrame with md DataFrame
md = md.merge(credits, on = 'id')
md = md.merge(keywords, on = 'id')

In [26]:
# Creating a small movies DataFrame from the links_small
smd = md[md['id'].isin(links_small)]
smd.shape

(9219, 28)

In [27]:
# We now have our cast, crew, genres and credits, all in one dataframe.
from ast import literal_eval

smd['cast'] = smd['cast'].apply(literal_eval)
smd['crew'] = smd['crew'].apply(literal_eval)
smd['keywords'] = smd['keywords'].apply(literal_eval)
smd['cast_size'] = smd['cast'].apply(lambda x: len(x))  # Storing the cast_size
smd['crew_size'] = smd['crew'].apply(lambda x: len(x))  # Storing the crew_size

In [28]:
# Defining a function that gets the director's name 
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan

In [29]:
# Applying the get_director function to the crew column to create smd['director'] column
smd['director'] = smd['crew'].apply(get_director)

In [30]:
# Arbitrarily we will choose the top 3 actors that appear in the credits list. 
smd['cast'] = smd['cast'].apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])
smd['cast'] = smd['cast'].apply(lambda x: x[:3] if len(x) >= 3 else x)  # Taking the top 3 actor from cast

In [31]:
smd['keywords'] = smd['keywords'].apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [32]:
# Strip Spaces and Convert to Lowercase from all our features. 
smd['cast'] = smd['cast'].apply(lambda x: [str.lower(i.replace(" ", "")) for i in x])

In [33]:
# Mention Director 3 times to give it more weight relative to the entire cast.
smd['director'] = smd['director'].astype('str').apply(lambda x: str.lower(x.replace(" ", "")))
smd['director'] = smd['director'].apply(lambda x: [x, x, x])

In [34]:
# Calculating the frequent counts of every keyword that appears in the dataset
s = smd.apply(lambda x: pd.Series(x['keywords']), axis = 1).stack().reset_index(level = 1, drop = True)
s.name = 'keywords'

In [35]:
s = s.value_counts()
s[: 5]

independent film        610
woman director          550
murder                  399
duringcreditsstinger    327
based on novel          318
Name: keywords, dtype: int64

In [36]:
# Removing keywords that occur only once
s = s[s > 1]

In [37]:
# We will convert every word to its stem so that words such as Dogs and Dog 
# are considered the same.
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer('english')
stemmer.stem('dogs')

'dog'

In [38]:
# Defining function filter_keywords() to create a list of words
def filter_keywords(x):
    words = []
    for i in x:
        if i in s:
            words.append(i)
    return words

In [39]:
# Converting the entries in keywords into stemmed words
smd['keywords'] = smd['keywords'].apply(filter_keywords)  #Applying the filter_keywords() function to keywords column
smd['keywords'] = smd['keywords'].apply(lambda x: [stemmer.stem(i) for i in x])  # Converting the entries in keywords column into stemmed words
smd['keywords'] = smd['keywords'].apply(lambda x: [str.lower(i.replace(" ", "")) for i in x])  # Removing spaces and converting the entries into lower case

In [40]:
smd.head()

   adult                        ...                                                                 director
0  False                        ...                               [johnlasseter, johnlasseter, johnlasseter]
1  False                        ...                                  [joejohnston, joejohnston, joejohnston]
2  False                        ...                               [howarddeutch, howarddeutch, howarddeutch]
3  False                        ...                         [forestwhitaker, forestwhitaker, forestwhitaker]
4  False                        ...                               [charlesshyer, charlesshyer, charlesshyer]

[5 rows x 31 columns]

In [41]:
# Combining 'keywords', 'cast', 'director' and genres columns in 'soup'
smd['soup'] = smd['keywords'] + smd['cast'] + smd['director'] + smd['genres']
smd['soup'] = smd['soup'].apply(lambda x: ' '.join(x))

In [42]:
# Convert a collection of text documents to a matrix of token counts
count = CountVectorizer(analyzer = 'word', ngram_range = (1, 2), min_df = 0, stop_words = 'english')
count_matrix = count.fit_transform(smd['soup'])

In [43]:
# Compute cosine similarity between samples in X and Y.
cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [44]:
smd = smd.reset_index()  # Reseting the indices within smd
titles = smd['title']  # Storing smd['title'] in titles variable
indices = pd.Series(smd.index, index = smd['title'])    # Creating a DataFrame of indices

In [45]:
get_recommendations('The Dark Knight').head(10)

8031         The Dark Knight Rises
6218                 Batman Begins
6623                  The Prestige
2085                     Following
7648                     Inception
4145                      Insomnia
3381                       Memento
8613                  Interstellar
7659    Batman: Under the Red Hood
1134                Batman Returns
Name: title, dtype: object

In [46]:
get_recommendations('Jurassic Park').head(10)

1251    The Lost World: Jurassic Park
6232                War of the Worlds
5869         Twilight Zone: The Movie
8005         The Adventures of Tintin
4173                  Minority Report
4458              Catch Me If You Can
2800                             Hook
906        E.T. the Extra-Terrestrial
3623                           Always
1362                          Amistad
Name: title, dtype: object

In [47]:
def improved_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse = True)
    sim_score = sim_scores[1:26]
    movie_indices = [i[0] for i in sim_scores]
    
    movies = smd.iloc[movie_indices][['title', 'vote_count', 'vote_average', 'year']]
    vote_counts = movies[movies['vote_count'].notnull()]['vote_count'].astype('int')
    vote_averages = movies[movies['vote_average'].notnull()]['vote_average'].astype('int')
    C = vote_averages.mean()
    m = vote_counts.quantile(0.60)
    qualified = movies[(movies['vote_count'] >= m) & (movies['vote_count'].notnull()) & (movies['vote_average'].notnull())]
    qualified = movies[(movies['vote_count'] >= m) & (movies['vote_count'].notnull()) & (movies['vote_average'].notnull())]
    qualified['vote_count'] = qualified['vote_count'].astype('int')
    qualified['vote_average'] = qualified['vote_average'].astype('int')
    qualified['wr'] = qualified.apply(weighted_rating, axis=1)
    qualified = qualified.sort_values('wr', ascending=False).head(10)
    return qualified

In [48]:
vote_counts = md[md['vote_count'].notnull()]['vote_count'].astype('int')
vote_averages = md[md['vote_average'].notnull()]['vote_average'].astype('int')
C = vote_averages.mean()
C

5.238696808510638

In [49]:
# The minimum votes required to be listed in the chart. We will use 95th percentile as our cutoff.
# i.e. For a movie to feature in the charts, it must have more votes than at least 95% of the movies in the list.
m = vote_counts.quantile(0.95)
m

425.0

In [50]:
# Defining the weighted_rating() function
def weighted_rating(x):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [51]:
# Getting recommedations from our model
improved_recommendations('The Dark Knight')

                                                  title    ...           wr
7648                                          Inception    ...     7.919065
6981                                    The Dark Knight    ...     7.907551
8613                                       Interstellar    ...     7.898936
2390                                         Fight Club    ...     7.883841
3899  The Lord of the Rings: The Fellowship of the Ring    ...     7.874042
266                                        Pulp Fiction    ...     7.870967
284                            The Shawshank Redemption    ...     7.866383
5074      The Lord of the Rings: The Return of the King    ...     7.864345
321                                        Forrest Gump    ...     7.863095
4436              The Lord of the Rings: The Two Towers    ...     7.854506

[10 rows x 5 columns]